DIG-1409: Add healthcheck.py for docker healthcheck fix
CanDIG/federation_service pull request #50
Opened 2024-02-01 19:10 UTC by lilyyangyi301

- Added the required python healthcheck script for the healthcheck fix.

2024-02-06 18:11 UTC, OrdiNeu requested changes
One quick change here, otherwise looks good :heavy_check_mark:

2024-02-06 18:11 UTC, OrdiNeu commented on candig_federation/healthcheck.py
> +    url = "http://candig.docker.internal:5080/federation/v1/service-info"
Need to swap this to use `{FEDERATION_SERVICE_URL}/v1/service-info`, in the same manner that you added KEYCLOAK_URL.

2024-02-06 19:31 UTC, lilyyangyi301 commented on candig_federation/healthcheck.py
> +    url = "http://candig.docker.internal:5080/federation/v1/service-info"
Fixed.

2024-02-07 21:27 UTC, lilyyangyi301 commented
Closed because no longer needed.

2024-02-07 21:27 UTC, closed without merging